apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
## build out list from manifests dir
# kustomize edit add resource manifests/*.yaml
## WARNING: do NOT add any sections below "resources:"
resources:
- manifests/appscode.yaml
- manifests/bitnami-labs-sealed-secrets.yaml
- manifests/bitnami.yaml
- manifests/deliveryhero.yaml
- manifests/gatekeeper.yaml
- manifests/kube-state-metrics.yaml
- manifests/kured.yaml
- manifests/podinfo.yaml
- manifests/portainer.yaml
- manifests/prometheus-community.yaml
- manifests/stakater.yaml
- manifests/wave-k8s.yaml
