apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: forecastle
    meta.helm.sh/release-namespace: kube-system
    external-dns.alpha.kubernetes.io/hostname: forecastle.mxnxpx.tk
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
  name: forecastle
  namespace: kube-system
spec:
  rules:
  - host: forecastle.10.195.65.109.nip.io
    http:
      paths:
      - backend:
          serviceName: forecastle
          servicePort: http
        path: /
        pathType: ImplementationSpecific
